version: '3'

services:
  karaoke-api:
    network_mode: host
    image: node:latest
    container_name: karaoke-api
    mem_limit: 1g
    restart: unless-stopped
    tty: true
    ports:
      - 3333:3333
    command:
      - sh
      - -c
      - |
        echo "alias l='ls -l'" >> ~/.bashrc
        cd /api
        yarn
        yarn server
    volumes:
      - ./:/api
    environment:
      - NODE_ENV=production
